version: "3.8"
services:
  bot:
    container_name: bot
    build:
      context: ./bot
      dockerfile: bot.Dockerfile
    env_file:
      - creds.env
    restart: always
    depends_on:
      - scheduler

  scheduler:
    container_name: scheduler
    build:
      context: ./scheduler
      dockerfile: scheduler.Dockerfile
    env_file:
      - creds.env
    restart: always
    depends_on:
      database:
        condition: service_healthy
      queue:
        condition: service_healthy

  database:
    container_name: database
    image: postgres:latest
    env_file:
      - creds.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  queue:
    container_name: queue
    image: rabbitmq:latest
    ports:
      - "5672:5672"    #amqp
      - "15672:15672"  #http
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db:

#version: "3.8"
#services:
#  bot:
#    container_name: bot
#    image: ruauka/bot:latest
#    env_file:
#      - creds.env
#    restart: always
#    depends_on:
#      - scheduler
#
#  scheduler:
#    container_name: scheduler
#    image: ruauka/scheduler:latest
#    env_file:
#      - creds.env
#    restart: always
#    depends_on:
#      database:
#        condition: service_healthy
#      queue:
#        condition: service_healthy
#
#  database:
#    container_name: database
#    image: postgres:latest
#    restart: always
#    env_file:
#      - creds.env
#    volumes:
#      - db:/var/lib/postgresql/data
#    restart: always
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#
#  queue:
#    image: rabbitmq:latest
#    container_name: queue
#    restart: always
#    healthcheck:
#      test: ["CMD", "rabbitmqctl", "status"]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#
#volumes:
#  db: