version: "3.8"
services:
#  bot:
#    container_name: bot
#    build:
#      context: ./bot
#      dockerfile: bot.Dockerfile
##    image: ruauka/bot:latest
#    depends_on:
#      - scheduler
#
#  scheduler:
#    container_name: scheduler
#    build:
#      context: ./scheduler
#      dockerfile: scheduler.Dockerfile
##    image: ruauka/scheduler:latest
#    depends_on:
#      queue:
#        condition: service_healthy

  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: crud
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  queue:
    image: rabbitmq:latest
    container_name: queue
    ports:
      - "5672:5672"    #amqp
      - "15672:15672"  #http
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5

volumes:
  db: