name: build

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build_push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Bot
        uses: docker/build-push-action@v3
        with:
          context: ./bot
          file: ./bot/bot.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bot:latest

      - name: Build and Push Scheduler
        uses: docker/build-push-action@v3
        with:
          context: ./scheduler
          file: ./scheduler/scheduler.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/scheduler:latest

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build_push
    steps:
      - name: SSH connect
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Login into DockerHub
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            # cd
            cd bot

            # Stop docker-compose
            docker-compose stop

            # Remove bot container and image
            docker rm bot && docker rmi ruauka/bot
      
            # Remove scheduler container and image
            docker rm scheduler && docker rmi ruauka/scheduler

            # Start docker-compose
            docker-compose up -d